var annotated_dup =
[
    [ "machine_learning", "d8/d77/namespacemachine__learning.html", "d8/d77/namespacemachine__learning" ],
    [ "statistics", "d2/dcf/namespacestatistics.html", "d2/dcf/namespacestatistics" ],
    [ "Btree", "d9/d90/struct_btree.html", "d9/d90/struct_btree" ],
    [ "cll", "d5/d15/classcll.html", "d5/d15/classcll" ],
    [ "compare", "d1/db3/structcompare.html", "d1/db3/structcompare" ],
    [ "Complex", "da/d5a/class_complex.html", "da/d5a/class_complex" ],
    [ "CycleCheck", "d3/dbb/class_cycle_check.html", "d3/dbb/class_cycle_check" ],
    [ "double_linked_list", "d9/dee/classdouble__linked__list.html", "d9/dee/classdouble__linked__list" ],
    [ "Edge", "d7/d77/class_edge.html", "d7/d77/class_edge" ],
    [ "Entry", "dd/d3b/struct_entry.html", "dd/d3b/struct_entry" ],
    [ "FenwickTree", "dd/d91/class_fenwick_tree.html", "dd/d91/class_fenwick_tree" ],
    [ "graph", "dd/d9b/classgraph.html", "dd/d9b/classgraph" ],
    [ "Graph", "da/d9a/class_graph.html", "da/d9a/class_graph" ],
    [ "Item", "db/d66/struct_item.html", "db/d66/struct_item" ],
    [ "large_number", "db/d82/classlarge__number.html", "db/d82/classlarge__number" ],
    [ "lca", "dd/df4/structlca.html", "dd/df4/structlca" ],
    [ "linkedlist", "d0/dff/structlinkedlist.html", "d0/dff/structlinkedlist" ],
    [ "list", "d8/d10/structlist.html", "d8/d10/structlist" ],
    [ "MinHeap", "d2/d05/class_min_heap.html", "d2/d05/class_min_heap" ],
    [ "MinHeapNode", "d5/d29/struct_min_heap_node.html", "d5/d29/struct_min_heap_node" ],
    [ "mst", "d1/d77/structmst.html", "d1/d77/structmst" ],
    [ "node", "d5/da1/structnode.html", "d5/da1/structnode" ],
    [ "Node", "db/d8b/struct_node.html", "db/d8b/struct_node" ],
    [ "Point", "d8/dc8/struct_point.html", "d8/dc8/struct_point" ],
    [ "query", "dd/d1b/structquery.html", "dd/d1b/structquery" ],
    [ "queue", "d2/d36/structqueue.html", "d2/d36/structqueue" ],
    [ "Queue", "d4/da4/class_queue.html", "d4/da4/class_queue" ],
    [ "Queue_Array", "d0/dd2/class_queue___array.html", "d0/dd2/class_queue___array" ],
    [ "SegmentIntersection", "d4/db4/struct_segment_intersection.html", "d4/db4/struct_segment_intersection" ],
    [ "Solution", "dd/d4f/class_solution.html", "dd/d4f/class_solution" ],
    [ "stack", "d1/dc2/classstack.html", "d1/dc2/classstack" ],
    [ "stack_linkedList", "d2/dc4/classstack__linked_list.html", "d2/dc4/classstack__linked_list" ],
    [ "tower", "d2/d2c/structtower.html", "d2/d2c/structtower" ],
    [ "trie", "d4/dd9/structtrie.html", "d4/dd9/structtrie" ],
    [ "Trie", "dd/d2f/class_trie.html", "dd/d2f/class_trie" ]
];