var namespaces_dup =
[
    [ "a1z26", "d8/d2a/namespacea1z26.html", null ],
    [ "abbreviation", "d0/df8/namespaceabbreviation.html", null ],
    [ "activations", "d5/d39/namespaceactivations.html", null ],
    [ "atbash", "de/db3/namespaceatbash.html", null ],
    [ "aystar_search", "db/ddc/namespaceaystar__search.html", null ],
    [ "backtracking", "db/dc0/namespacebacktracking.html", "db/dc0/namespacebacktracking" ],
    [ "base64_encoding", "d9/dc9/namespacebase64__encoding.html", null ],
    [ "bidirectional_dijkstra", "d4/d13/namespacebidirectional__dijkstra.html", null ],
    [ "binomial", "d7/d7a/namespacebinomial.html", null ],
    [ "bit_manipulation", "d7/d81/namespacebit__manipulation.html", [
      [ "isPowerOfTwo", "d7/d81/namespacebit__manipulation.html#a5032470c9974bbd6ec254bf296530a5f", null ],
      [ "next_higher_number", "d7/d81/namespacebit__manipulation.html#a4b76571a2a04fa99c30a96eca9997f0e", null ]
    ] ],
    [ "boruvkas_minimum_spanning_tree", "d8/d64/namespaceboruvkas__minimum__spanning__tree.html", null ],
    [ "caesar", "dd/d81/namespacecaesar.html", null ],
    [ "ciphers", "d6/d4e/namespaceciphers.html", "d6/d4e/namespaceciphers" ],
    [ "circular_linked_list", "d4/dcd/namespacecircular__linked__list.html", null ],
    [ "count_bits_flip", "d4/d38/namespacecount__bits__flip.html", null ],
    [ "count_of_set_bits", "dd/dae/namespacecount__of__set__bits.html", null ],
    [ "count_of_trailing_ciphers_in_factorial_n", "dc/d2f/namespacecount__of__trailing__ciphers__in__factorial__n.html", null ],
    [ "cut_rod", "d8/d36/namespacecut__rod.html", null ],
    [ "cycle_detection", "da/d82/namespacecycle__detection.html", null ],
    [ "cycle_sort", "d4/dfb/namespacecycle__sort.html", null ],
    [ "data_structures", "d5/d3c/namespacedata__structures.html", "d5/d3c/namespacedata__structures" ],
    [ "depth_first_search", "d8/da7/namespacedepth__first__search.html", null ],
    [ "disjoint_union", "de/db4/namespacedisjoint__union.html", null ],
    [ "divide_and_conquer", "dd/dba/namespacedivide__and__conquer.html", null ],
    [ "dnf_sort", "d9/d75/namespacednf__sort.html", null ],
    [ "double_hashing", "d0/d65/namespacedouble__hashing.html", "d0/d65/namespacedouble__hashing" ],
    [ "dp", "df/d88/namespacedp.html", null ],
    [ "dynamic_programming", "dd/d24/namespacedynamic__programming.html", [
      [ "is_armstrong", "dd/d24/namespacedynamic__programming.html#af046365a8d77a1267acc082f86135a26", null ],
      [ "LIS", "dd/d24/namespacedynamic__programming.html#a0a2215194e58786c34db1ccaf8031079", null ],
      [ "lps", "dd/d24/namespacedynamic__programming.html#afe9f45b6e30ee187509da2d1d0093412", null ],
      [ "maxCircularSum", "dd/d24/namespacedynamic__programming.html#a5239174fa0d987f2c67edc1f2af82beb", null ]
    ] ],
    [ "false_position", "df/dea/namespacefalse__position.html", null ],
    [ "fibonacci_sum", "d3/dc9/namespacefibonacci__sum.html", null ],
    [ "find_non_repeating_integer", "d2/da7/namespacefind__non__repeating__integer.html", null ],
    [ "geometric_dist", "dd/d8a/namespacegeometric__dist.html", null ],
    [ "geometry", "d5/d5f/namespacegeometry.html", null ],
    [ "gram_schmidt", "d4/d0f/namespacegram__schmidt.html", null ],
    [ "graph", "df/dce/namespacegraph.html", "df/dce/namespacegraph" ],
    [ "graph_coloring", "d7/d08/namespacegraph__coloring.html", null ],
    [ "greedy_algorithms", "d2/d90/namespacegreedy__algorithms.html", "d2/d90/namespacegreedy__algorithms" ],
    [ "ground_to_ground_projectile_motion", "d0/d20/namespaceground__to__ground__projectile__motion.html", null ],
    [ "hamming_distance", "d4/d1c/namespacehamming__distance.html", null ],
    [ "hashing", "d6/d0c/namespacehashing.html", null ],
    [ "heavy_light_decomposition", "db/d6f/namespaceheavy__light__decomposition.html", null ],
    [ "horspool", "d5/d02/namespacehorspool.html", null ],
    [ "house_robber", "d2/de1/namespacehouse__robber.html", null ],
    [ "inorder_successor_of_bst", "dd/d74/namespaceinorder__successor__of__bst.html", null ],
    [ "interpolation_search", "d1/d64/namespaceinterpolation__search.html", null ],
    [ "inversion", "d9/d13/namespaceinversion.html", null ],
    [ "is_graph_bipartite", "de/d83/namespaceis__graph__bipartite.html", null ],
    [ "iterative_tree_traversals", "dd/d73/namespaceiterative__tree__traversals.html", null ],
    [ "jarvis", "d5/da7/namespacejarvis.html", null ],
    [ "k_nearest_neighbors", "d7/d4c/namespacek__nearest__neighbors.html", null ],
    [ "kadane", "d6/d74/namespacekadane.html", null ],
    [ "karatsuba_algorithm", "de/d41/namespacekaratsuba__algorithm.html", null ],
    [ "Knapsack", "d7/daf/namespace_knapsack.html", null ],
    [ "knight_tour", "d1/db6/namespaceknight__tour.html", null ],
    [ "layers", "d5/d2c/namespacelayers.html", null ],
    [ "linear_probing", "d8/d89/namespacelinear__probing.html", "d8/d89/namespacelinear__probing" ],
    [ "linear_recurrence_matrix", "d9/dd1/namespacelinear__recurrence__matrix.html", null ],
    [ "linked_list", "d3/db0/namespacelinked__list.html", null ],
    [ "list_array", "d9/d27/namespacelist__array.html", null ],
    [ "lru_cache", "d8/dcd/namespacelru__cache.html", null ],
    [ "machine_learning", "d8/d77/namespacemachine__learning.html", "d8/d77/namespacemachine__learning" ],
    [ "magic_sequence", "d8/d93/namespacemagic__sequence.html", null ],
    [ "manacher", "d8/dc6/namespacemanacher.html", null ],
    [ "math", "dd/d47/namespacemath.html", "dd/d47/namespacemath" ],
    [ "MD5", "dd/d43/namespace_m_d5.html", null ],
    [ "median_search", "da/dd4/namespacemedian__search.html", null ],
    [ "merge_insertion", "de/d0a/namespacemerge__insertion.html", null ],
    [ "midpoint_rule", "d9/daa/namespacemidpoint__rule.html", null ],
    [ "mincoins_topdown", "d5/db8/namespacemincoins__topdown.html", null ],
    [ "Minimum", "d4/d12/namespace_minimum.html", null ],
    [ "modular_division", "d1/d64/namespacemodular__division.html", null ],
    [ "monte_carlo", "d0/da4/namespacemonte__carlo.html", null ],
    [ "morse", "d6/d8d/namespacemorse.html", null ],
    [ "n_bonacci", "de/d36/namespacen__bonacci.html", null ],
    [ "n_queens", "d3/da1/namespacen__queens.html", null ],
    [ "n_queens_all_solutions", "df/d44/namespacen__queens__all__solutions.html", null ],
    [ "n_queens_optimized", "d8/d14/namespacen__queens__optimized.html", null ],
    [ "ncr_modulo_p", "d4/db9/namespacencr__modulo__p.html", null ],
    [ "neural_network", "d0/d2e/namespaceneural__network.html", null ],
    [ "numerical_methods", "d1/de0/namespacenumerical__methods.html", [
      [ "babylonian_method", "d1/de0/namespacenumerical__methods.html#a28e67885f8606564cc8335f483f63309", null ],
      [ "FastFourierTransform", "d1/de0/namespacenumerical__methods.html#a158fd271b9a53e8f3f60b08b18857150", null ],
      [ "InverseFastFourierTransform", "d1/de0/namespacenumerical__methods.html#aee56dc85997b8cd42bad71a5d6bd2d93", null ]
    ] ],
    [ "operations_on_datastructures", "da/d6d/namespaceoperations__on__datastructures.html", "da/d6d/namespaceoperations__on__datastructures" ],
    [ "others", "d0/d6f/namespaceothers.html", "d0/d6f/namespaceothers" ],
    [ "palindrome_partitioning", "d5/d89/namespacepalindrome__partitioning.html", null ],
    [ "pancake_sort", "df/d10/namespacepancake__sort.html", null ],
    [ "physics", "d5/dd0/namespacephysics.html", null ],
    [ "postfix_expression", "d4/de6/namespacepostfix__expression.html", null ],
    [ "prefix_sum_array", "d7/d88/namespaceprefix__sum__array.html", null ],
    [ "probability", "d4/ded/namespaceprobability.html", null ],
    [ "qr_algorithm", "d2/d3b/namespaceqr__algorithm.html", [
      [ "eigen_values", "d2/d3b/namespaceqr__algorithm.html#a28e2fa3e803abaea6c568dc45d69d8cc", null ],
      [ "operator<<", "d2/d3b/namespaceqr__algorithm.html#adfbdf47277c8cfee229b05b72f1f7834", null ],
      [ "operator<<", "d2/d3b/namespaceqr__algorithm.html#a257425cb2365359da51c6fe6741834d8", null ],
      [ "qr_decompose", "d2/d3b/namespaceqr__algorithm.html#a73ce637634fc49e1d10d190eb388ebf1", null ],
      [ "vector_dot", "d2/d3b/namespaceqr__algorithm.html#a8ea313a1a1b5f9d0e3e332c29c6446ec", null ],
      [ "vector_mag", "d2/d3b/namespaceqr__algorithm.html#ad16da2183db22378435042f26af43d5f", null ],
      [ "vector_proj", "d2/d3b/namespaceqr__algorithm.html#a6d3c7dce1f142141f509d09f6c0e25dc", null ]
    ] ],
    [ "quadratic_probing", "d4/dd2/namespacequadratic__probing.html", "d4/dd2/namespacequadratic__probing" ],
    [ "queue_using_array", "d9/d70/namespacequeue__using__array.html", null ],
    [ "quick_sort", "d0/d2b/namespacequick__sort.html", null ],
    [ "radix_sort", "da/dda/namespaceradix__sort.html", null ],
    [ "random_pivot_quick_sort", "de/d6b/namespacerandom__pivot__quick__sort.html", null ],
    [ "range_queries", "dd/d69/namespacerange__queries.html", "dd/d69/namespacerange__queries" ],
    [ "rat_maze", "d9/d60/namespacerat__maze.html", null ],
    [ "reverse_binary_tree", "dc/dc5/namespacereverse__binary__tree.html", null ],
    [ "runge_kutta", "d2/de7/namespacerunge__kutta.html", null ],
    [ "saddleback", "d0/dda/namespacesaddleback.html", null ],
    [ "search", "d9/dca/namespacesearch.html", null ],
    [ "selection_sort_recursive", "df/d4a/namespaceselection__sort__recursive.html", null ],
    [ "setKthBit", "d8/d88/namespaceset_kth_bit.html", null ],
    [ "SHA", "de/dd3/namespace_s_h_a.html", null ],
    [ "shortest_common_supersequence", "d3/deb/namespaceshortest__common__supersequence.html", null ],
    [ "simpson_method", "d3/d6d/namespacesimpson__method.html", null ],
    [ "sorting", "d5/d91/namespacesorting.html", [
      [ "binary_search", "d5/d91/namespacesorting.html#a034d8b276518a902962e87d3158b64fd", null ],
      [ "gnomeSort", "d5/d91/namespacesorting.html#aa3677f87b5b4756bc77e9e34c5f27935", null ],
      [ "gnomeSort", "d5/d91/namespacesorting.html#a2f8bc626eb57acae24a94636a23af6a1", null ],
      [ "insertionSort", "d5/d91/namespacesorting.html#a8fe6bac9e03f58abcc2ce26ef3de1b5f", null ],
      [ "insertionSort", "d5/d91/namespacesorting.html#a78cb2f3b97b6db2c062b2a1df05c9ea9", null ],
      [ "insertionSort_binsrch", "d5/d91/namespacesorting.html#a5f4bc75cca6dd8294af2d0e328006c68", null ],
      [ "merge", "d5/d91/namespacesorting.html#aa26de383227859210f14dcf12201a079", null ],
      [ "non_recursive_merge_sort", "d5/d91/namespacesorting.html#ae97f4dd815654c4682f564afd718e824", null ],
      [ "non_recursive_merge_sort", "d5/d91/namespacesorting.html#a140d913e42fb94176a0b2c8b29a80420", null ],
      [ "non_recursive_merge_sort", "d5/d91/namespacesorting.html#a27236b8d3df3832e1f1225576a122534", null ],
      [ "pigeonSort", "d5/d91/namespacesorting.html#a0e9e1b21a1684585e9e50f9afe4d53a3", null ],
      [ "quicksort", "d5/d91/namespacesorting.html#a9f59fe72dacc1f1218ef3c303d843168", null ],
      [ "quicksort", "d5/d91/namespacesorting.html#a6eb67c2f91c98cf4464f75b5882022de", null ],
      [ "randomized_bogosort", "d5/d91/namespacesorting.html#affc6ee160142cd017f8c4b213437d0fd", null ],
      [ "recursive_bubble_sort", "d5/d91/namespacesorting.html#ae3a775d99dbbb94c130a973df0cfddcf", null ],
      [ "shell_sort", "d5/d91/namespacesorting.html#af2c5b92cbfe73f63f6074c61b0a45331", null ],
      [ "shell_sort", "d5/d91/namespacesorting.html#a5669396c6a6b1e14b97589b6e37980aa", null ],
      [ "shell_sort", "d5/d91/namespacesorting.html#a4d76603c54d3dc56146e92d10a043924", null ],
      [ "shuffle", "d5/d91/namespacesorting.html#a7bfe11bd4703eacd1dab93f25ec639c5", null ]
    ] ],
    [ "sparse_table", "d9/d55/namespacesparse__table.html", null ],
    [ "spirograph", "da/dd3/namespacespirograph.html", [
      [ "spirograph", "da/dd3/namespacespirograph.html#aeca22dbe4563358960e907a40cd3e1ac", null ],
      [ "test", "da/dd3/namespacespirograph.html#a8e83a64e8443fff1e5ffdc1c299c1e99", null ]
    ] ],
    [ "stack_using_queue", "df/d1c/namespacestack__using__queue.html", null ],
    [ "statistics", "d2/dcf/namespacestatistics.html", "d2/dcf/namespacestatistics" ],
    [ "std", "d8/dcc/namespacestd.html", "d8/dcc/namespacestd" ],
    [ "strand", "d8/d1d/namespacestrand.html", null ],
    [ "strassens_multiplication", "d3/d91/namespacestrassens__multiplication.html", null ],
    [ "string_search", "d9/d03/namespacestring__search.html", [
      [ "brute_force", "d9/d03/namespacestring__search.html#aeb2cd81064717aedd62bfb096b1a73d8", null ],
      [ "check_if_equal", "d9/d03/namespacestring__search.html#aebe07cea289a13142503d98be7df11fd", null ],
      [ "create_hash", "d9/d03/namespacestring__search.html#a8fb0bc932ba8b582c9f4c71338d050f8", null ],
      [ "getFailureArray", "d9/d03/namespacestring__search.html#a996573527312d5255e1495b879e8a34f", null ],
      [ "kmp", "d9/d03/namespacestring__search.html#a26a58225ce7d3fa9d4c2f5349a65ed93", null ],
      [ "rabin_karp", "d9/d03/namespacestring__search.html#a21c673d56cbf67b1d2ee4d869185b7d9", null ],
      [ "recalculate_hash", "d9/d03/namespacestring__search.html#aed769d565b705a9b3e0eb1ec74088893", null ]
    ] ],
    [ "strings", "df/dcb/namespacestrings.html", null ],
    [ "subarray_sum", "df/d74/namespacesubarray__sum.html", null ],
    [ "sublist_search", "d9/def/namespacesublist__search.html", null ],
    [ "subset_sum", "dc/d3a/namespacesubset__sum.html", null ],
    [ "Subsets", "de/d95/namespace_subsets.html", null ],
    [ "sudoku_solver", "d8/d9f/namespacesudoku__solver.html", null ],
    [ "tests", "d9/df4/namespacetests.html", [
      [ "test1", "d9/df4/namespacetests.html#a167c24bd817469ae47358d12e034f2d5", null ],
      [ "test2", "d9/df4/namespacetests.html#abdd77344d4af8fd56d14a5cabbf2f669", null ],
      [ "test3", "d9/df4/namespacetests.html#aa515639572647508b94986489aab6d76", null ],
      [ "test4", "d9/df4/namespacetests.html#a2b9769e44683dcb67fe1083ad91e134d", null ],
      [ "test5", "d9/df4/namespacetests.html#af7b81d7a1534216af6a36a80135beb86", null ],
      [ "test6", "d9/df4/namespacetests.html#aacafde185abd8670abee51157f273dc2", null ]
    ] ],
    [ "travellingSalesman_bitmanipulation", "d7/d3f/namespacetravelling_salesman__bitmanipulation.html", null ],
    [ "tree_234", "d6/dab/namespacetree__234.html", null ],
    [ "trie_operations", "df/d8e/namespacetrie__operations.html", null ],
    [ "trie_using_hashmap", "d7/d0a/namespacetrie__using__hashmap.html", null ],
    [ "util_functions", "d3/d17/namespaceutil__functions.html", null ],
    [ "vector_cross", "d4/d91/namespacevector__cross.html", null ],
    [ "vigenere", "d6/da2/namespacevigenere.html", null ],
    [ "wave_sort", "d9/d21/namespacewave__sort.html", null ],
    [ "wiggle_sort", "d0/d52/namespacewiggle__sort.html", null ],
    [ "wildcard_matching", "db/d03/namespacewildcard__matching.html", null ],
    [ "windowed_median", "dd/d21/namespacewindowed__median.html", null ],
    [ "word_break", "d6/d53/namespaceword__break.html", null ],
    [ "XOR", "d7/d47/namespace_x_o_r.html", null ]
];