var searchData=
[
  ['va_5flist_2324',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['val_2325',['val',['../de/d9d/classdata__structures_1_1linked__list_1_1link.html#acf96f3a9a1d3b15268c38e8822300c11',1,'data_structures::linked_list::link::val()'],['../d5/d66/classrange__queries_1_1per_seg_tree_1_1_node.html#acc044f787c90b815773726d7fdfdaccf',1,'range_queries::perSegTree::Node::val()']]],
  ['valarray_2326',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valarray_3c_20double_20_3e_2327',['valarray&lt; double &gt;',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valid_2328',['valid',['http://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()']]],
  ['value_2329',['value',['../d9/d49/structdata__structures_1_1_node.html#a6b973b0bded99b0c0bd84e887bf8c731',1,'data_structures::Node::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()'],['../dd/db6/structbinary__search__tree_1_1bst__node.html#a09da9e5b801ede4764bc812975ff7f29',1,'binary_search_tree::bst_node::value()']]],
  ['value_5fcomp_2330',['value_comp',['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()']]],
  ['value_5fcompare_2331',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap&lt; K, T &gt;::value_compare']]],
  ['value_5for_2332',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional']]],
  ['values_2333',['values',['../d2/d2c/structtower.html#a3ebb75c13c57d51a8a1ba1ea54a515e9',1,'tower']]],
  ['variance_2334',['variance',['../d8/dab/classstatistics_1_1stats__computer2.html#af6198817084276113b3c064e87ce0555',1,'statistics::stats_computer2::variance()'],['../d7/d7c/classstatistics_1_1stats__computer1.html#a27f0a03e2fd2254f1c81fe668226bd92',1,'statistics::stats_computer1::variance()']]],
  ['vec_2335',['vec',['../d8/d28/classrange__queries_1_1per_seg_tree.html#a8ff495d2f389b4aaa54449c26c6078f3',1,'range_queries::perSegTree']]],
  ['vector_2336',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std::vector&lt; T &gt;'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_3c_20bool_20_3e_2337',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20double_20_3e_2338',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20geometry_3a_3ajarvis_3a_3apoint_20_3e_2339',['vector&lt; geometry::jarvis::Point &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int_20_3e_2340',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int64_5ft_20_3e_2341',['vector&lt; int64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20machine_5flearning_3a_3aneural_5fnetwork_3a_3alayers_3a_3adenselayer_20_3e_2342',['vector&lt; machine_learning::neural_network::layers::DenseLayer &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20operations_5fon_5fdatastructures_3a_3atrie_5foperations_3a_3atnode_20_2a_20_3e_2343',['vector&lt; operations_on_datastructures::trie_operations::Tnode * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20int_20_3e_20_3e_2344',['vector&lt; std::list&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20int_2c_20int_20_3e_20_3e_2345',['vector&lt; std::pair&lt; int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20data_5fstructures_3a_3anode_20_3e_20_3e_2346',['vector&lt; std::shared_ptr&lt; data_structures::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20node_20_3e_20_3e_2347',['vector&lt; std::shared_ptr&lt; Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20range_5fqueries_3a_3apersegtree_3a_3anode_20_3e_20_3e_2348',['vector&lt; std::shared_ptr&lt; range_queries::perSegTree::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20int_2c_20int_2c_20int_20_3e_20_3e_2349',['vector&lt; std::tuple&lt; int, int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avalarray_3c_20double_20_3e_20_3e_2350',['vector&lt; std::valarray&lt; double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20int_20_3e_20_3e_2351',['vector&lt; std::vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20uint64_5ft_20_3e_2352',['vector&lt; uint64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20char_20_3e_2353',['vector&lt; unsigned char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20int_20_3e_2354',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20x_20_3e_2355',['vector&lt; X &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_5fcross_2356',['vector_cross',['../d4/d91/namespacevector__cross.html',1,'']]],
  ['vector_5fcross_5fproduct_2ecpp_2357',['vector_cross_product.cpp',['../df/d66/vector__cross__product_8cpp.html',1,'']]],
  ['vector_5fdot_2358',['vector_dot',['../d2/d3b/namespaceqr__algorithm.html#a8ea313a1a1b5f9d0e3e332c29c6446ec',1,'qr_algorithm']]],
  ['vector_5fimportant_5ffunctions_2ecpp_2359',['vector_important_functions.cpp',['../d3/d61/vector__important__functions_8cpp.html',1,'']]],
  ['vector_5fmag_2360',['vector_mag',['../d2/d3b/namespaceqr__algorithm.html#ad16da2183db22378435042f26af43d5f',1,'qr_algorithm']]],
  ['vector_5fops_2ehpp_2361',['vector_ops.hpp',['../d8/d95/vector__ops_8hpp.html',1,'']]],
  ['vector_5fproj_2362',['vector_proj',['../d2/d3b/namespaceqr__algorithm.html#a5422c76bfa322620de611083bd518d71',1,'qr_algorithm']]],
  ['vfprintf_2363',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vfscanf_2364',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vfwprintf_2365',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vfwscanf_2366',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vigenere_2367',['vigenere',['../d6/da2/namespacevigenere.html',1,'']]],
  ['vigenere_5fcipher_2ecpp_2368',['vigenere_cipher.cpp',['../dd/d12/vigenere__cipher_8cpp.html',1,'']]],
  ['vprintf_2369',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vscanf_2370',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vsnprintf_2371',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsprintf_2372',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsscanf_2373',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vswprintf_2374',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vswscanf_2375',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vwprintf_2376',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vwscanf_2377',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]]
];
