var searchData=
[
  ['a_0',['A',['../da/d37/structdata__structures_1_1sparse__table_1_1_sparse__table.html#ab78620742305a35ff2f8d61179f47d3e',1,'data_structures::sparse_table::Sparse_table']]],
  ['a_1',['a',['http://en.cppreference.com/w/cpp/numeric/random/extreme_value_distribution/params.html',0,'std::extreme_value_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution/params.html',0,'std::uniform_real_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/weibull_distribution/params.html',0,'std::weibull_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution/params.html',0,'std::uniform_int_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/cauchy_distribution/params.html',0,'std::cauchy_distribution::a()']]],
  ['a_20new_20directory_2',['Integrating CMake in a new directory',['../d6/dcd/md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md34',1,'']]],
  ['a_20program_3',['Typical structure of a program',['../d6/dcd/md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md31',1,'']]],
  ['a_20right_20node_20subtree_4',['Case 2: The given node does not have a right node/subtree',['../d4/d32/inorder__successor__of__bst_8cpp.html#autotoc_md90',1,'']]],
  ['a_20tree_5',['a tree',['../d8/d90/iterative__tree__traversals_8cpp.html#autotoc_md95',1,'Iterative Inorder Traversal of a tree'],['../dc/de1/recursive__tree__traversal_8cpp.html#autotoc_md99',1,'Iterative Inorder Traversal of a tree'],['../d8/d90/iterative__tree__traversals_8cpp.html#autotoc_md94',1,'Iterative Postorder Traversal of a tree'],['../dc/de1/recursive__tree__traversal_8cpp.html#autotoc_md101',1,'Iterative Postorder Traversal of a tree'],['../d8/d90/iterative__tree__traversals_8cpp.html#autotoc_md93',1,'Iterative Preorder Traversal of a tree'],['../dc/de1/recursive__tree__traversal_8cpp.html#autotoc_md100',1,'Iterative Preorder Traversal of a tree']]],
  ['a1z26_6',['a1z26',['../d8/d2a/namespacea1z26.html',1,'']]],
  ['a1z26_5fcipher_2ecpp_7',['a1z26_cipher.cpp',['../de/db6/a1z26__cipher_8cpp.html',1,'']]],
  ['a_5fstar_5fsearch_8',['a_star_search',['../da/d02/classmachine__learning_1_1aystar__search_1_1_ay_star_search.html#a48284e156fdd48fd0c41008c7e48f201',1,'machine_learning::aystar_search::AyStarSearch']]],
  ['abbreviation_9',['abbreviation',['../d0/df8/namespaceabbreviation.html',1,'abbreviation'],['../d7/d73/abbreviation_8cpp.html#af53b2f647bee9c5b75ef8dd9ef685dc8',1,'dynamic_programming::abbreviation::abbreviation()']]],
  ['abbreviation_2ecpp_10',['abbreviation.cpp',['../d7/d73/abbreviation_8cpp.html',1,'']]],
  ['abbreviation_5frecursion_11',['abbreviation_recursion',['../d7/d73/abbreviation_8cpp.html#add60b8858720bf217df22d992d0fefaa',1,'dynamic_programming::abbreviation']]],
  ['abort_12',['abort',['http://en.cppreference.com/w/cpp/utility/program/abort.html',0,'std']]],
  ['abs_13',['abs',['../da/d5a/class_complex.html#ae5b51b749ea4964104b9527af9d8f556',1,'Complex']]],
  ['abs_28float_29_14',['abs(float)',['http://en.cppreference.com/w/cpp/numeric/math/fabs.html',0,'std']]],
  ['abs_28int_29_15',['abs(int)',['http://en.cppreference.com/w/cpp/numeric/math/abs.html',0,'std']]],
  ['absoluteprecision_16',['absolutePrecision',['../dc/dfe/ternary__search_8cpp.html#ae01eda5098801bb6b5b778828fb4fddc',1,'ternary_search.cpp']]],
  ['accumulate_17',['accumulate',['http://en.cppreference.com/w/cpp/algorithm/accumulate.html',0,'std']]],
  ['accuracy_18',['ACCURACY',['../da/df2/durand__kerner__roots_8cpp.html#af270a96662132d0385cb6b4637c5a689',1,'durand_kerner_roots.cpp']]],
  ['accuracy_19',['accuracy',['../d6/d30/classmachine__learning_1_1adaline.html#aa23d60262f917f35836ef4b1c1d9f7d3',1,'machine_learning::adaline']]],
  ['acos_20',['acos',['http://en.cppreference.com/w/cpp/numeric/math/acos.html',0,'std']]],
  ['acosh_21',['acosh',['http://en.cppreference.com/w/cpp/numeric/math/acosh.html',0,'std']]],
  ['actions_22',['GitHub Actions',['../d6/dcd/md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md40',1,'']]],
  ['activation_23',['activation',['../d6/d30/classmachine__learning_1_1adaline.html#a082f758fb55fe19f22b3df66f89b2325',1,'machine_learning::adaline']]],
  ['activations_24',['activations',['../d5/d39/namespaceactivations.html',1,'']]],
  ['adaline_25',['adaline',['../d6/d30/classmachine__learning_1_1adaline.html',1,'machine_learning::adaline'],['../d6/d30/classmachine__learning_1_1adaline.html#a0acbe32aaab897e7939e5b0454035b8c',1,'machine_learning::adaline::adaline()']]],
  ['adaline_5flearning_2ecpp_26',['adaline_learning.cpp',['../d5/db0/adaline__learning_8cpp.html',1,'']]],
  ['add_27',['add',['../d9/dae/classdata__structures_1_1_bitset.html#a17dbe1b1d559302312e8091f82f7499c',1,'data_structures::Bitset::add()'],['../dc/dd4/classdata__structures_1_1_bloom_filter.html#a67bed8ef62fcb1f33b6c72df47dcf840',1,'data_structures::BloomFilter::add()'],['../dd/d1c/classhash__chain.html#a6b4b4de1a8c96f98a63a77f650a9dcff',1,'hash_chain::add()'],['../de/dcf/classoperations__on__datastructures_1_1reverse__binary__tree_1_1_binary_tree.html#a534645d1aabdf1a7e5897c85376f173d',1,'operations_on_datastructures::reverse_binary_tree::BinaryTree::add()'],['../da/d41/uint128__t_8hpp.html#a3ff77262ffd6743df5b808d41382a6f3',1,'add():&#160;uint128_t.hpp'],['../d0/d65/namespacedouble__hashing.html#a79a9c914a6c68275b3640303d7faad8a',1,'double_hashing::add()'],['../d8/d89/namespacelinear__probing.html#a16d34fd3511626a83ab00665d7bc34d1',1,'linear_probing::add()'],['../d4/dd2/namespacequadratic__probing.html#a00ebcc6d39653eccc26f8432efbfc8d9',1,'quadratic_probing::add()'],['../de/d47/string__fibonacci_8cpp.html#a28052eee05d43c2ebc5147c52bd50c35',1,'add():&#160;string_fibonacci.cpp']]],
  ['add_5fconst_28',['add_const',['http://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5fcv_29',['add_cv',['http://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['add_5fdigit_30',['add_digit',['../db/d82/classlarge__number.html#a60c436d1a1c5e3795d6177d3815ad615',1,'large_number']]],
  ['add_5fedge_31',['add_edge',['../dc/d61/classgraph_1_1_graph.html#a877b2cba40d8d46dde6fb4209effed19',1,'graph::Graph::add_edge()'],['../d2/daa/classgreedy__algorithms_1_1dijkstra_1_1_graph.html#a224b6efacbad55d59e11b046f792fe79',1,'greedy_algorithms::dijkstra::Graph::add_edge()'],['../d1/d51/classrange__queries_1_1heavy__light__decomposition_1_1_tree.html#a79ab4601c4a95c0902ac04e779e5f54d',1,'range_queries::heavy_light_decomposition::Tree::add_edge()']]],
  ['add_5flvalue_5freference_32',['add_lvalue_reference',['http://en.cppreference.com/w/cpp/types/add_reference.html',0,'std']]],
  ['add_5fpointer_33',['add_pointer',['http://en.cppreference.com/w/cpp/types/add_pointer.html',0,'std']]],
  ['add_5frvalue_5freference_34',['add_rvalue_reference',['http://en.cppreference.com/w/cpp/types/add_reference.html',0,'std']]],
  ['add_5fstrings_35',['add_strings',['../da/dd3/karatsuba__algorithm__for__fast__multiplication_8cpp.html#ad76f5cac3ef8dc034f6abb99b64c2b20',1,'divide_and_conquer::karatsuba_algorithm']]],
  ['add_5fvolatile_36',['add_volatile',['http://en.cppreference.com/w/cpp/types/add_cv.html',0,'std']]],
  ['addbinary_37',['addBinary',['../de/df6/classgreedy__algorithms_1_1_binary_addition.html#a801fd1ec5cda76b0bb82cbf23ed4d527',1,'greedy_algorithms::BinaryAddition']]],
  ['addedge_38',['addEdge',['../da/d9a/class_graph.html#af765dda8f21280e1cecea19e129f1bc5',1,'Graph::addEdge(Edge const &amp;edge)'],['../da/d9a/class_graph.html#ac85c63bcca4764a621f9f8609a8e5910',1,'Graph::addEdge(unsigned int source, unsigned int destination)'],['../d8/d69/classgraph_1_1_h_k_graph.html#a3b49011c09cf90a116ab53bef61cd95a',1,'graph::HKGraph::addEdge()'],['../de/d00/classgraph_1_1is__graph__bipartite_1_1_graph.html#a816cda7e563198f778fd32e03992763b',1,'graph::is_graph_bipartite::Graph::addEdge()'],['../d5/dec/classgraph_1_1topological__sort_1_1_graph.html#a57036210706a45b9363563252393a345',1,'graph::topological_sort::Graph::addEdge()'],['../d7/d07/bidirectional__dijkstra_8cpp.html#a69172365aebde9be1997157f6f80e0cf',1,'graph::bidirectional_dijkstra::addEdge()'],['../df/dce/namespacegraph.html#a9125ceb66bfbec3093bba64c2c1e99e2',1,'graph::addEdge(std::vector&lt; std::vector&lt; int &gt; &gt; *adj, int u, int v)'],['../df/dce/namespacegraph.html#ad4016cfc80485a43748895a2c26c7d08',1,'graph::addEdge(std::vector&lt; std::vector&lt; size_t &gt; &gt; *adj, size_t u, size_t v)'],['../da/d4b/depth__first__search__with__stack_8cpp.html#aadebe9c855821d6515ca5b171222ef7b',1,'graph::depth_first_search::addEdge()'],['../df/dce/namespacegraph.html#a0e30e0dca68cb6e4f671440819b35b6a',1,'graph::addEdge()']]],
  ['addinfo_39',['addInfo',['../d0/d65/namespacedouble__hashing.html#a9c652b2e467e5d250dfe3bed83b12560',1,'double_hashing::addInfo()'],['../d8/d89/namespacelinear__probing.html#a16680b8a37d442c2f208faa286e33908',1,'linear_probing::addInfo()'],['../d4/dd2/namespacequadratic__probing.html#a312143ed316d48978084c025ff8d9768',1,'quadratic_probing::addInfo()']]],
  ['addition_40',['addition',['../df/d6b/namespaceciphers_1_1elliptic__curve__key__exchange.html#acc5fe9c2032fb7582c38a20d1fa69bcf',1,'ciphers::elliptic_curve_key_exchange']]],
  ['addition_5frule_2ecpp_41',['addition_rule.cpp',['../d6/d4a/addition__rule_8cpp.html',1,'']]],
  ['addition_5frule_5fdependent_42',['addition_rule_dependent',['../d6/d4a/addition__rule_8cpp.html#a565ffcbbdbe496ced37250bc8dc36bc0',1,'addition_rule.cpp']]],
  ['addition_5frule_5findependent_43',['addition_rule_independent',['../d6/d4a/addition__rule_8cpp.html#a4adfd055c758546456d440ee9133555d',1,'addition_rule.cpp']]],
  ['addprocess_44',['addProcess',['../dd/dca/class_f_c_f_s.html#a8fbfe4d85f7576b4a7aade07d29fbd69',1,'FCFS']]],
  ['address_45',['address',['http://en.cppreference.com/w/cpp/memory/allocator/address.html',0,'std::allocator']]],
  ['address_20of_20parent_20nodes_46',['Method 1: Use parent pointer (store the address of parent nodes)',['../d4/d32/inorder__successor__of__bst_8cpp.html#autotoc_md91',1,'']]],
  ['addressing_47',['Open Addressing',['../d4/d39/group__open__addressing.html',1,'']]],
  ['addressof_48',['addressof',['http://en.cppreference.com/w/cpp/memory/addressof.html',0,'std']]],
  ['addvertices_49',['addVertices',['../da/d9a/class_graph.html#ac5a4d9a4f894a179198936042c778413',1,'Graph']]],
  ['adj_50',['adj',['../d8/d69/classgraph_1_1_h_k_graph.html#a35893def7a1c5cd60907b4893117796f',1,'graph::HKGraph::adj'],['../de/d00/classgraph_1_1is__graph__bipartite_1_1_graph.html#ab0efcfa04fff8616aff0062522d1483f',1,'graph::is_graph_bipartite::Graph::adj']]],
  ['adjacency_5flist_51',['adjacency_list',['../dc/d61/classgraph_1_1_graph.html#acebf0505d625b043bb9c8c27c7a8def0',1,'graph::Graph']]],
  ['adjacent_5fdifference_52',['adjacent_difference',['http://en.cppreference.com/w/cpp/algorithm/adjacent_difference.html',0,'std']]],
  ['adjacent_5ffind_53',['adjacent_find',['http://en.cppreference.com/w/cpp/algorithm/adjacent_find.html',0,'std']]],
  ['adopt_5flock_5ft_54',['adopt_lock_t',['http://en.cppreference.com/w/cpp/thread/lock_tag_t.html',0,'std']]],
  ['advance_55',['advance',['http://en.cppreference.com/w/cpp/iterator/advance.html',0,'std']]],
  ['algorithm_56',['Algorithm',['../dc/dfb/atbash__cipher_8cpp.html#autotoc_md0',1,'Algorithm'],['../d6/d2c/caesar__cipher_8cpp.html#autotoc_md1',1,'Algorithm'],['../dd/d12/vigenere__cipher_8cpp.html#autotoc_md2',1,'Algorithm'],['../d3/d4c/xor__cipher_8cpp.html#autotoc_md3',1,'Algorithm'],['../da/dc3/linked__list_8cpp.html#autotoc_md41',1,'Algorithm'],['../d7/d00/list__array_8cpp.html#autotoc_md42',1,'Algorithm'],['../d8/df0/queue__using__array_8cpp.html#autotoc_md43',1,'Algorithm'],['../d6/d05/reverse__a__linked__list_8cpp.html#autotoc_md44',1,'Algorithm'],['../db/d16/0__1__knapsack_8cpp.html#autotoc_md69',1,'Algorithm'],['../d7/d73/abbreviation_8cpp.html#autotoc_md70',1,'Algorithm'],['../d6/d10/cut__rod_8cpp.html#autotoc_md71',1,'Algorithm'],['../db/dca/kadane2_8cpp.html#autotoc_md72',1,'Algorithm'],['../da/d52/minimum__edit__distance_8cpp.html#autotoc_md73',1,'Algorithm'],['../d7/dcb/_unbounded__0__1___knapsack_8cpp.html#autotoc_md74',1,'Algorithm'],['../d4/d8d/jarvis__algorithm_8cpp.html#autotoc_md75',1,'Algorithm'],['../d8/d99/connected__components__with__dsu_8cpp.html#autotoc_md76',1,'Algorithm'],['../d1/d9a/hopcroft__karp_8cpp.html#autotoc_md82',1,'Algorithm'],['../d5/d96/md5_8cpp.html#autotoc_md83',1,'Algorithm'],['../d8/d7a/sha1_8cpp.html#autotoc_md84',1,'Algorithm'],['../dd/d47/namespacemath.html#autotoc_md85',1,'Algorithm'],['../d4/d38/power__of__two_8cpp.html#autotoc_md86',1,'Algorithm'],['../d5/d33/gram__schmidt_8cpp.html#autotoc_md88',1,'Algorithm'],['../d1/ded/windowed__median_8cpp.html#autotoc_md102',1,'Algorithm'],['../d5/d45/sublist__search_8cpp.html#autotoc_md108',1,'Algorithm'],['../d5/ddb/bogo__sort_8cpp.html#autotoc_md110',1,'Algorithm'],['../d2/d26/count__inversions_8cpp.html#autotoc_md115',1,'Algorithm'],['../d3/df9/recursive__bubble__sort_8cpp.html#autotoc_md116',1,'Algorithm'],['../d5/d4c/group__sorting.html',1,'Sorting Algorithm']]],
  ['algorithm_20analysis_20best_20case_20worst_20case_20average_20case_57',['Bubble Sort Algorithm Analysis (Best Case - Worst Case - Average Case)',['../d8/d13/bubble__sort_8cpp.html#autotoc_md111',1,'']]],
  ['algorithm_20explanation_58',['Algorithm explanation',['../d3/db3/lru__cache_8cpp.html#autotoc_md97',1,'']]],
  ['algorithms_59',['Algorithms',['../d5/d88/md__d_i_r_e_c_t_o_r_y.html#autotoc_md48',1,'Cpu Scheduling Algorithms'],['../d5/d88/md__d_i_r_e_c_t_o_r_y.html#autotoc_md56',1,'Greedy Algorithms'],['../d9/d66/group__machine__learning.html',1,'Machine Learning Algorithms']]],
  ['algorithms_20c_60',['The Algorithms - C++',['../index.html',1,'']]],
  ['align_61',['align',['http://en.cppreference.com/w/cpp/memory/align.html',0,'std']]],
  ['aligned_5fstorage_62',['aligned_storage',['http://en.cppreference.com/w/cpp/types/aligned_storage.html',0,'std']]],
  ['aligned_5funion_63',['aligned_union',['http://en.cppreference.com/w/cpp/types/aligned_union.html',0,'std']]],
  ['alignment_5fof_64',['alignment_of',['http://en.cppreference.com/w/cpp/types/alignment_of.html',0,'std']]],
  ['aliquot_5fsum_65',['aliquot_sum',['../dd/d47/namespacemath.html#ab37f3a7302a84179aae682c79d8390bf',1,'math']]],
  ['aliquot_5fsum_2ecpp_66',['aliquot_sum.cpp',['../de/d99/aliquot__sum_8cpp.html',1,'']]],
  ['all_67',['all',['http://en.cppreference.com/w/cpp/utility/bitset/all_any_none.html',0,'std::bitset']]],
  ['all_5fof_68',['all_of',['http://en.cppreference.com/w/cpp/algorithm/all_any_none_of.html',0,'std']]],
  ['allocate_69',['allocate',['http://en.cppreference.com/w/cpp/memory/allocator_traits/allocate.html',0,'std::allocator_traits::allocate()'],['http://en.cppreference.com/w/cpp/memory/allocator/allocate.html',0,'std::allocator::allocate()'],['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor/allocate.html',0,'std::scoped_allocator_adaptor::allocate()']]],
  ['allocate_5fshared_70',['allocate_shared',['http://en.cppreference.com/w/cpp/memory/shared_ptr/allocate_shared.html',0,'std']]],
  ['allocator_71',['allocator',['http://en.cppreference.com/w/cpp/memory/allocator.html',0,'std::allocator&lt; T &gt;'],['http://en.cppreference.com/w/cpp/memory/allocator/allocator.html',0,'std::allocator::allocator()']]],
  ['allocator_5farg_5ft_72',['allocator_arg_t',['http://en.cppreference.com/w/cpp/memory/allocator_arg_t.html',0,'std']]],
  ['allocator_5ftraits_73',['allocator_traits',['http://en.cppreference.com/w/cpp/memory/allocator_traits.html',0,'std']]],
  ['alpha_74',['alpha',['http://en.cppreference.com/w/cpp/numeric/random/gamma_distribution/params.html',0,'std::gamma_distribution']]],
  ['always_5fnoconv_75',['always_noconv',['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',0,'std::codecvt::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',0,'std::codecvt_byname::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',0,'std::codecvt_utf8::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',0,'std::codecvt_utf8_utf16::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',0,'std::codecvt_utf16::always_noconv()']]],
  ['analysis_20best_20case_20worst_20case_20average_20case_76',['Bubble Sort Algorithm Analysis (Best Case - Worst Case - Average Case)',['../d8/d13/bubble__sort_8cpp.html#autotoc_md111',1,'']]],
  ['analyzer_77',['Static Code Analyzer',['../d6/dcd/md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md38',1,'']]],
  ['and_20conquer_78',['Divide And Conquer',['../d5/d88/md__d_i_r_e_c_t_o_r_y.html#autotoc_md50',1,'']]],
  ['and_20maintainers_79',['Guidelines for reviewers and maintainers',['../d7/d1b/md__r_e_v_i_e_w_e_r___c_o_d_e.html',1,'']]],
  ['and_20not_20matching_20edges_80',['Matching and Not-Matching edges',['../d1/d9a/hopcroft__karp_8cpp.html#autotoc_md78',1,'']]],
  ['and_5ftest_81',['and_test',['../d3/db2/boyer__moore_8cpp.html#acb8f69e7901ee7459d98bd4b9dda79d9',1,'boyer_moore.cpp']]],
  ['ans_82',['ans',['../d7/d35/matrix__exponentiation_8cpp.html#ad8389ed58fd0ec66df248014775ad1fa',1,'matrix_exponentiation.cpp']]],
  ['any_83',['any',['http://en.cppreference.com/w/cpp/utility/bitset/all_any_none.html',0,'std::bitset']]],
  ['any_5fof_84',['any_of',['http://en.cppreference.com/w/cpp/algorithm/all_any_none_of.html',0,'std']]],
  ['aplhabet_5fsize_85',['APLHABET_SIZE',['../d3/db2/boyer__moore_8cpp.html#a77c872c08612d7b8861ba13bc9881cbd',1,'boyer_moore.cpp']]],
  ['append_86',['append',['http://en.cppreference.com/w/cpp/string/basic_string/append.html',0,'std::string::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',0,'std::basic_string::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',0,'std::wstring::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',0,'std::u16string::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',0,'std::u32string::append()']]],
  ['apply_5ffunction_87',['apply_function',['../d8/d77/namespacemachine__learning.html#ad0bdc88e5f1be47c46c0f0c8ebf754bb',1,'machine_learning']]],
  ['approximate_5fpi_88',['approximate_pi',['../dd/d47/namespacemath.html#abf7f2a6d91f1ca6c89698792aea3f188',1,'math']]],
  ['approximate_5fpi_2ecpp_89',['approximate_pi.cpp',['../d0/d51/approximate__pi_8cpp.html',1,'']]],
  ['are_5falmost_5fequal_90',['are_almost_equal',['../d0/d6f/namespaceothers.html#aa17dc6d061dff34f6b9a610bc5e26703',1,'others']]],
  ['are_5famicable_91',['are_amicable',['../dd/d47/namespacemath.html#a8e6eede206201db0d1dbb618fa969bec',1,'math']]],
  ['area_2ecpp_92',['area.cpp',['../dc/d82/area_8cpp.html',1,'']]],
  ['arg_93',['arg',['../da/d5a/class_complex.html#ae1e03712837450549e0c9b4017533a41',1,'Complex']]],
  ['argmax_94',['argmax',['../d8/d77/namespacemachine__learning.html#a50480fccfb39de20ca47f1bf51ecb6ec',1,'machine_learning']]],
  ['armstrong_5fnumber_2ecpp_95',['armstrong_number.cpp',['../d1/db7/dynamic__programming_2armstrong__number_8cpp.html',1,'']]],
  ['arr_96',['arr',['../d6/d04/classdata__structures_1_1queue__using__array_1_1_queue___array.html#ae69a0bf6c9921b37c516c8a4d2fb904d',1,'data_structures::queue_using_array::Queue_Array::arr'],['../d0/d3e/classdata__structures_1_1trie.html#a362dd78748a1f01ab019e55fd6098a8b',1,'data_structures::trie::arr']]],
  ['array_97',['array',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20data_5fstructures_3a_3atree_5f234_3a_3anode_20_2a_2c_204_20_3e_98',['array&lt; data_structures::tree_234::Node *, 4 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20float_2c_2020_20_3e_99',['array&lt; float, 20 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20int_2c_20maxnode_20_3e_100',['array&lt; int, maxNode &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20int16_5ft_2c_20max_5fsize_20_3e_101',['array&lt; int16_t, max_size &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20int64_5ft_2c_203_20_3e_102',['array&lt; int64_t, 3 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20int64_5ft_2c_20n_20_3e_103',['array&lt; int64_t, N &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20std_3a_3aarray_3c_20int_2c_202_20_3e_2c_20maxnode_20_3e_104',['array&lt; std::array&lt; int, 2 &gt;, maxNode &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20std_3a_3aarray_3c_20int64_5ft_2c_20n_20_3e_2c_20m_20_3e_105',['array&lt; std::array&lt; int64_t, N &gt;, M &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20std_3a_3aarray_3c_20uint32_5ft_2c_203_20_3e_2c_203_20_3e_106',['array&lt; std::array&lt; uint32_t, 3 &gt;, 3 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20uint32_5ft_2c_208_20_3e_107',['array&lt; uint32_t, 8 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_3c_20uint64_5ft_2c_20n_20_3e_108',['array&lt; uint64_t, N &gt;',['http://en.cppreference.com/w/cpp/container/array.html',0,'std']]],
  ['array_5fleft_5frotation_2ecpp_109',['array_left_rotation.cpp',['../d9/d14/array__left__rotation_8cpp.html',1,'']]],
  ['array_5fright_5frotation_2ecpp_110',['array_right_rotation.cpp',['../d6/d57/array__right__rotation_8cpp.html',1,'']]],
  ['asctime_111',['asctime',['http://en.cppreference.com/w/cpp/chrono/c/asctime.html',0,'std']]],
  ['asin_112',['asin',['http://en.cppreference.com/w/cpp/numeric/math/asin.html',0,'std']]],
  ['asinh_113',['asinh',['http://en.cppreference.com/w/cpp/numeric/math/asinh.html',0,'std']]],
  ['ask_5fdata_114',['ask_data',['../d8/d41/namespacegames_1_1memory__game.html#a5714d97649c0edd57b4fb449799676a3',1,'games::memory_game']]],
  ['assertarray_115',['assertArray',['../da/d18/quadratic__equations__complex__numbers_8cpp.html#af7a6d4e3dc85a6288c8f1f7094830c5a',1,'quadratic_equations_complex_numbers.cpp']]],
  ['assign_116',['assign',['http://en.cppreference.com/w/cpp/container/vector/assign.html',0,'std::vector::assign()'],['http://en.cppreference.com/w/cpp/string/char_traits/assign.html',0,'std::char_traits::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',0,'std::string::assign()'],['http://en.cppreference.com/w/cpp/regex/basic_regex/assign.html',0,'std::regex::assign()'],['http://en.cppreference.com/w/cpp/regex/basic_regex/assign.html',0,'std::basic_regex::assign()'],['http://en.cppreference.com/w/cpp/regex/basic_regex/assign.html',0,'std::wregex::assign()'],['http://en.cppreference.com/w/cpp/container/forward_list/assign.html',0,'std::forward_list::assign()'],['http://en.cppreference.com/w/cpp/error/error_code/assign.html',0,'std::error_code::assign()'],['http://en.cppreference.com/w/cpp/container/deque/assign.html',0,'std::deque::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',0,'std::basic_string::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',0,'std::wstring::assign()'],['http://en.cppreference.com/w/cpp/utility/functional/function/assign.html',0,'std::function::assign()'],['http://en.cppreference.com/w/cpp/error/error_condition/assign.html',0,'std::error_condition::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',0,'std::u16string::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',0,'std::u32string::assign()'],['http://en.cppreference.com/w/cpp/container/list/assign.html',0,'std::list::assign()']]],
  ['assign_5fresults_117',['assign_results',['../d8/d41/namespacegames_1_1memory__game.html#a3ceeea62d8fa6c563e2c66359fd73413',1,'games::memory_game']]],
  ['async_118',['async',['http://en.cppreference.com/w/cpp/thread/async.html',0,'std']]],
  ['at_119',['at',['http://en.cppreference.com/w/cpp/container/dynarray/at.html',0,'std::dynarray::at()'],['http://en.cppreference.com/w/cpp/container/vector/at.html',0,'std::vector::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',0,'std::string::at()'],['http://en.cppreference.com/w/cpp/container/unordered_map/at.html',0,'std::unordered_map::at()'],['http://en.cppreference.com/w/cpp/container/deque/at.html',0,'std::deque::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',0,'std::basic_string::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',0,'std::wstring::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',0,'std::u16string::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',0,'std::u32string::at()'],['http://en.cppreference.com/w/cpp/container/map/at.html',0,'std::map::at()'],['http://en.cppreference.com/w/cpp/container/array/at.html',0,'std::array::at()']]],
  ['at_5fquick_5fexit_120',['at_quick_exit',['http://en.cppreference.com/w/cpp/utility/program/at_quick_exit.html',0,'std']]],
  ['atan_121',['atan',['http://en.cppreference.com/w/cpp/numeric/math/atan.html',0,'std']]],
  ['atan2_122',['atan2',['http://en.cppreference.com/w/cpp/numeric/math/atan2.html',0,'std']]],
  ['atanh_123',['atanh',['http://en.cppreference.com/w/cpp/numeric/math/atanh.html',0,'std']]],
  ['atbash_124',['atbash',['../de/db3/namespaceatbash.html',1,'']]],
  ['atbash_5fcipher_125',['atbash_cipher',['../dc/dfb/atbash__cipher_8cpp.html#a8f7dd4dcd3df7c512c20482afc2dbb9d',1,'ciphers::atbash']]],
  ['atbash_5fcipher_2ecpp_126',['atbash_cipher.cpp',['../dc/dfb/atbash__cipher_8cpp.html',1,'']]],
  ['atexit_127',['atexit',['http://en.cppreference.com/w/cpp/utility/program/atexit.html',0,'std']]],
  ['atof_128',['atof',['http://en.cppreference.com/w/cpp/string/byte/atof.html',0,'std']]],
  ['atoi_129',['atoi',['http://en.cppreference.com/w/cpp/string/byte/atoi.html',0,'std']]],
  ['atol_130',['atol',['http://en.cppreference.com/w/cpp/string/byte/atoi.html',0,'std']]],
  ['atoll_131',['atoll',['http://en.cppreference.com/w/cpp/string/byte/atoi.html',0,'std']]],
  ['atomic_132',['atomic',['http://en.cppreference.com/w/cpp/atomic/atomic.html',0,'std::atomic&lt; T &gt;'],['http://en.cppreference.com/w/cpp/atomic/atomic/atomic.html',0,'std::atomic::atomic()']]],
  ['atomic_5fcompare_5fexchange_5fstrong_133',['atomic_compare_exchange_strong',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',0,'std']]],
  ['atomic_5fcompare_5fexchange_5fstrong_5fexplicit_134',['atomic_compare_exchange_strong_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',0,'std']]],
  ['atomic_5fcompare_5fexchange_5fweak_135',['atomic_compare_exchange_weak',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',0,'std']]],
  ['atomic_5fcompare_5fexchange_5fweak_5fexplicit_136',['atomic_compare_exchange_weak_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',0,'std']]],
  ['atomic_5fexchange_137',['atomic_exchange',['http://en.cppreference.com/w/cpp/atomic/atomic_exchange.html',0,'std']]],
  ['atomic_5fexchange_5fexplicit_138',['atomic_exchange_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_exchange.html',0,'std']]],
  ['atomic_5ffetch_5fadd_139',['atomic_fetch_add',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_add.html',0,'std']]],
  ['atomic_5ffetch_5fadd_5fexplicit_140',['atomic_fetch_add_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_add.html',0,'std']]],
  ['atomic_5ffetch_5fand_141',['atomic_fetch_and',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',0,'std']]],
  ['atomic_5ffetch_5fand_5fexplicit_142',['atomic_fetch_and_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',0,'std']]],
  ['atomic_5ffetch_5for_143',['atomic_fetch_or',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_or.html',0,'std']]],
  ['atomic_5ffetch_5for_5fexplicit_144',['atomic_fetch_or_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_or.html',0,'std']]],
  ['atomic_5ffetch_5fsub_145',['atomic_fetch_sub',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',0,'std']]],
  ['atomic_5ffetch_5fsub_5fexplicit_146',['atomic_fetch_sub_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',0,'std']]],
  ['atomic_5ffetch_5fxor_147',['atomic_fetch_xor',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_xor.html',0,'std']]],
  ['atomic_5ffetch_5fxor_5fexplicit_148',['atomic_fetch_xor_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_xor.html',0,'std']]],
  ['atomic_5fflag_149',['atomic_flag',['http://en.cppreference.com/w/cpp/atomic/atomic_flag.html',0,'std::atomic_flag'],['http://en.cppreference.com/w/cpp/atomic/atomic_flag/atomic_flag.html',0,'std::atomic_flag::atomic_flag()']]],
  ['atomic_5finit_150',['atomic_init',['http://en.cppreference.com/w/cpp/atomic/atomic_init.html',0,'std']]],
  ['atomic_5fis_5flock_5ffree_151',['atomic_is_lock_free',['http://en.cppreference.com/w/cpp/atomic/atomic_is_lock_free.html',0,'std']]],
  ['atomic_5fload_152',['atomic_load',['http://en.cppreference.com/w/cpp/atomic/atomic_load.html',0,'std']]],
  ['atomic_5fload_5fexplicit_153',['atomic_load_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_load.html',0,'std']]],
  ['atomic_5fsignal_5ffence_154',['atomic_signal_fence',['http://en.cppreference.com/w/cpp/atomic/atomic_signal_fence.html',0,'std']]],
  ['atomic_5fstore_155',['atomic_store',['http://en.cppreference.com/w/cpp/atomic/atomic_store.html',0,'std']]],
  ['atomic_5fstore_5fexplicit_156',['atomic_store_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_store.html',0,'std']]],
  ['atomic_5fthread_5ffence_157',['atomic_thread_fence',['http://en.cppreference.com/w/cpp/atomic/atomic_thread_fence.html',0,'std']]],
  ['attribution_158',['Attribution',['../d3/dd7/md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md15',1,'']]],
  ['augmenting_20paths_159',['Augmenting paths',['../d1/d9a/hopcroft__karp_8cpp.html#autotoc_md80',1,'']]],
  ['auto_5fptr_160',['auto_ptr',['http://en.cppreference.com/w/cpp/memory/auto_ptr.html',0,'std::auto_ptr&lt; T &gt;'],['http://en.cppreference.com/w/cpp/memory/auto_ptr/auto_ptr.html',0,'std::auto_ptr::auto_ptr()']]],
  ['auxiliary_5fq_161',['auxiliary_q',['../db/d5b/structdata__structures_1_1stack__using__queue_1_1_stack.html#a2f80f87fc6f6ded938426698bba89323',1,'data_structures::stack_using_queue::Stack']]],
  ['availarray_162',['AvailArray',['../d3/dce/linkedlist__implentation__usingarray_8cpp.html#aed19b403f559fc5d5a4bce724f9e263c',1,'linkedlist_implentation_usingarray.cpp']]],
  ['average_20case_163',['Average Case',['../d8/d13/bubble__sort_8cpp.html#autotoc_md114',1,'Average Case'],['../d8/d13/bubble__sort_8cpp.html#autotoc_md111',1,'Bubble Sort Algorithm Analysis (Best Case - Worst Case - Average Case)']]],
  ['avltree_2ecpp_164',['avltree.cpp',['../d8/dee/avltree_8cpp.html',1,'']]],
  ['aystar_5fsearch_165',['aystar_search',['../db/ddc/namespaceaystar__search.html',1,'']]],
  ['aystarsearch_166',['AyStarSearch',['../da/d02/classmachine__learning_1_1aystar__search_1_1_ay_star_search.html',1,'machine_learning::aystar_search::AyStarSearch&lt; Puzzle &gt;'],['../da/d02/classmachine__learning_1_1aystar__search_1_1_ay_star_search.html#abaff2ea6d309e1133fd95bbd1e39946e',1,'machine_learning::aystar_search::AyStarSearch::AyStarSearch()']]]
];
