var searchData=
[
  ['v_5fstack_0',['v_stack',['../dc/d13/classdivide__and__conquer_1_1strassens__multiplication_1_1_matrix.html#af12ceffdc07cc87eca8a4a8ac87d60fe',1,'divide_and_conquer::strassens_multiplication::Matrix']]],
  ['va_5flist_1',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['val_2',['val',['../d5/d66/classrange__queries_1_1per_seg_tree_1_1_node.html#acc044f787c90b815773726d7fdfdaccf',1,'range_queries::perSegTree::Node::val'],['../d7/da4/struct_list_node.html#a58389d1d1fc5430c2f4ce7c5d5dc48b3',1,'ListNode::val'],['../de/d9d/classdata__structures_1_1linked__list_1_1link.html#acf96f3a9a1d3b15268c38e8822300c11',1,'data_structures::linked_list::link::val()']]],
  ['valarray_3',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valarray_3c_20double_20_3e_4',['valarray&lt; double &gt;',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valid_5',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()']]],
  ['value_6',['value',['../dd/db6/structbinary__search__tree_1_1bst__node.html#a09da9e5b801ede4764bc812975ff7f29',1,'binary_search_tree::bst_node::value'],['../d9/d49/structdata__structures_1_1_node.html#a6b973b0bded99b0c0bd84e887bf8c731',1,'data_structures::Node::value'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()']]],
  ['value_5fcomp_7',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()']]],
  ['value_5fcompare_8',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap&lt; K, T &gt;::value_compare']]],
  ['value_5for_9',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional']]],
  ['values_10',['values',['../d2/d2c/structtower.html#a3ebb75c13c57d51a8a1ba1ea54a515e9',1,'tower::values'],['../d8/d7c/classoperations__on__datastructures_1_1circular__linked__list_1_1_circular_linked_list.html#a53611ec1fef92eeeb875aea1bde1e4de',1,'operations_on_datastructures::circular_linked_list::CircularLinkedList::values()'],['../d8/d7c/classoperations__on__datastructures_1_1circular__linked__list_1_1_circular_linked_list.html#a03a896b34d27fda69049827e0c4dab42',1,'operations_on_datastructures::circular_linked_list::CircularLinkedList::values(Node *root)']]],
  ['variance_11',['variance',['../d7/d7c/classstatistics_1_1stats__computer1.html#a27f0a03e2fd2254f1c81fe668226bd92',1,'statistics::stats_computer1::variance()'],['../d8/dab/classstatistics_1_1stats__computer2.html#af6198817084276113b3c064e87ce0555',1,'statistics::stats_computer2::variance()'],['../da/d19/classprobability_1_1geometric__dist_1_1geometric__distribution.html#aea8b0d649f0dc9a6f8baf3341a0b4960',1,'probability::geometric_dist::geometric_distribution::variance()']]],
  ['vec_12',['vec',['../d8/d28/classrange__queries_1_1per_seg_tree.html#a8ff495d2f389b4aaa54449c26c6078f3',1,'range_queries::perSegTree']]],
  ['vector_13',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std::vector&lt; T &gt;'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_3c_20bool_20_3e_14',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20double_20_3e_15',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20geometry_3a_3ajarvis_3a_3apoint_20_3e_16',['vector&lt; geometry::jarvis::Point &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int_20_3e_17',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int64_5ft_20_3e_18',['vector&lt; int64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20machine_5flearning_3a_3aneural_5fnetwork_3a_3alayers_3a_3adenselayer_20_3e_19',['vector&lt; machine_learning::neural_network::layers::DenseLayer &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20operations_5fon_5fdatastructures_3a_3atrie_5foperations_3a_3atnode_20_2a_20_3e_20',['vector&lt; operations_on_datastructures::trie_operations::Tnode * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20size_5ft_20_3e_21',['vector&lt; size_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3afunction_3c_20std_3a_3asize_5ft_28t_29_3e_20_3e_22',['vector&lt; std::function&lt; std::size_t(T)&gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20int_20_3e_20_3e_23',['vector&lt; std::list&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20int8_5ft_2c_20int8_5ft_20_3e_20_3e_24',['vector&lt; std::pair&lt; int8_t, int8_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20data_5fstructures_3a_3anode_20_3e_20_3e_25',['vector&lt; std::shared_ptr&lt; data_structures::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20node_20_3e_20_3e_26',['vector&lt; std::shared_ptr&lt; Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20range_5fqueries_3a_3apersegtree_3a_3anode_20_3e_20_3e_27',['vector&lt; std::shared_ptr&lt; range_queries::perSegTree::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3asize_5ft_20_3e_28',['vector&lt; std::size_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e_29',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20int_2c_20int_2c_20int_20_3e_20_3e_30',['vector&lt; std::tuple&lt; int, int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20s_2c_20t_2c_20e_2c_20double_2c_20double_2c_20double_20_3e_20_3e_31',['vector&lt; std::tuple&lt; S, T, E, double, double, double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avalarray_3c_20double_20_3e_20_3e_32',['vector&lt; std::valarray&lt; double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20double_20_3e_20_3e_33',['vector&lt; std::vector&lt; double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20int_20_3e_20_3e_34',['vector&lt; std::vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_35',['vector&lt; std::vector&lt; T &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20uint64_5ft_20_3e_36',['vector&lt; uint64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20char_20_3e_37',['vector&lt; unsigned char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20int_20_3e_38',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20x_20_3e_39',['vector&lt; X &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_5fcross_40',['vector_cross',['../d4/d91/namespacevector__cross.html',1,'']]],
  ['vector_5fcross_5fproduct_2ecpp_41',['vector_cross_product.cpp',['../df/d66/vector__cross__product_8cpp.html',1,'']]],
  ['vector_5fdot_42',['vector_dot',['../d2/d3b/namespaceqr__algorithm.html#a8ea313a1a1b5f9d0e3e332c29c6446ec',1,'qr_algorithm']]],
  ['vector_5fimportant_5ffunctions_2ecpp_43',['vector_important_functions.cpp',['../d3/d61/vector__important__functions_8cpp.html',1,'']]],
  ['vector_5fmag_44',['vector_mag',['../d2/d3b/namespaceqr__algorithm.html#ad16da2183db22378435042f26af43d5f',1,'qr_algorithm']]],
  ['vector_5fops_2ehpp_45',['vector_ops.hpp',['../d8/d95/vector__ops_8hpp.html',1,'']]],
  ['vector_5fproj_46',['vector_proj',['../d2/d3b/namespaceqr__algorithm.html#a6d3c7dce1f142141f509d09f6c0e25dc',1,'qr_algorithm']]],
  ['vfprintf_47',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vfscanf_48',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vfwprintf_49',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vfwscanf_50',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vigenere_51',['vigenere',['../d6/da2/namespacevigenere.html',1,'']]],
  ['vigenere_5fcipher_2ecpp_52',['vigenere_cipher.cpp',['../dd/d12/vigenere__cipher_8cpp.html',1,'']]],
  ['volume_2ecpp_53',['volume.cpp',['../da/d39/volume_8cpp.html',1,'']]],
  ['vprintf_54',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vscanf_55',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vsnprintf_56',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsprintf_57',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsscanf_58',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vswprintf_59',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vswscanf_60',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vwprintf_61',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vwscanf_62',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]]
];
