var searchData=
[
  ['x_0',['x',['../d8/dc8/struct_point.html#ab99c56589bc8ad5fa5071387110a5bc7',1,'Point']]],
  ['x_5f_1',['X_',['../da/d94/classmachine__learning_1_1k__nearest__neighbors_1_1_knn.html#a16ddc13621eec6ac5f83658b3401a581',1,'machine_learning::k_nearest_neighbors::Knn']]],
  ['xalloc_2',['xalloc',['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_ios::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::ios_base::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wistream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::strstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::istrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wiostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_ifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::ostrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wfstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::basic_iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wstringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::wistringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',0,'std::ifstream::xalloc()']]],
  ['xor_3',['XOR',['../d7/d47/namespace_x_o_r.html',1,'']]],
  ['xor_5fcipher_2ecpp_4',['xor_cipher.cpp',['../d3/d4c/xor__cipher_8cpp.html',1,'']]],
  ['xsgetn_5',['xsgetn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::basic_filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::wstringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::wfilebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::wstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::strstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::basic_stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::basic_streambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',0,'std::streambuf::xsgetn()']]],
  ['xsputn_6',['xsputn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::basic_filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::wstringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::wfilebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::wstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::strstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::basic_stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::basic_streambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',0,'std::streambuf::xsputn()']]]
];
