var searchData=
[
  ['va_5flist_2059',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['val_2060',['val',['../de/d9d/classdata__structures_1_1linked__list_1_1link.html#acf96f3a9a1d3b15268c38e8822300c11',1,'data_structures::linked_list::link']]],
  ['valarray_2061',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valarray_3c_20double_20_3e_2062',['valarray&lt; double &gt;',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valid_2063',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()']]],
  ['value_2064',['value',['../d9/d49/structdata__structures_1_1_node.html#a6b973b0bded99b0c0bd84e887bf8c731',1,'data_structures::Node::value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()']]],
  ['value_5fcomp_2065',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()']]],
  ['value_5fcompare_2066',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map&lt; K, T &gt;::value_compare']]],
  ['value_5for_2067',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional']]],
  ['values_2068',['values',['../d2/d2c/structtower.html#a3ebb75c13c57d51a8a1ba1ea54a515e9',1,'tower']]],
  ['variance_2069',['variance',['../d7/d7c/classstatistics_1_1stats__computer1.html#a27f0a03e2fd2254f1c81fe668226bd92',1,'statistics::stats_computer1::variance()'],['../d8/dab/classstatistics_1_1stats__computer2.html#af6198817084276113b3c064e87ce0555',1,'statistics::stats_computer2::variance()']]],
  ['vector_2070',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std::vector&lt; T &gt;'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_3c_20bool_20_3e_2071',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20double_20_3e_2072',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20geometry_3a_3ajarvis_3a_3apoint_20_3e_2073',['vector&lt; geometry::jarvis::Point &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int_20_3e_2074',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20machine_5flearning_3a_3aneural_5fnetwork_3a_3alayers_3a_3adenselayer_20_3e_2075',['vector&lt; machine_learning::neural_network::layers::DenseLayer &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20int_20_3e_20_3e_2076',['vector&lt; std::list&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20data_5fstructures_3a_3anode_20_3e_20_3e_2077',['vector&lt; std::shared_ptr&lt; data_structures::Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20node_20_3e_20_3e_2078',['vector&lt; std::shared_ptr&lt; Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20int_2c_20int_2c_20int_20_3e_20_3e_2079',['vector&lt; std::tuple&lt; int, int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avalarray_3c_20double_20_3e_20_3e_2080',['vector&lt; std::valarray&lt; double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20int_20_3e_20_3e_2081',['vector&lt; std::vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20uint64_5ft_20_3e_2082',['vector&lt; uint64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20char_20_3e_2083',['vector&lt; unsigned char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20int_20_3e_2084',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20x_20_3e_2085',['vector&lt; X &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_5fdot_2086',['vector_dot',['../d2/d3b/namespaceqr__algorithm.html#a8ea313a1a1b5f9d0e3e332c29c6446ec',1,'qr_algorithm']]],
  ['vector_5fimportant_5ffunctions_2ecpp_2087',['vector_important_functions.cpp',['../d3/d61/vector__important__functions_8cpp.html',1,'']]],
  ['vector_5fmag_2088',['vector_mag',['../d2/d3b/namespaceqr__algorithm.html#ad16da2183db22378435042f26af43d5f',1,'qr_algorithm']]],
  ['vector_5fops_2ehpp_2089',['vector_ops.hpp',['../d8/d95/vector__ops_8hpp.html',1,'']]],
  ['vector_5fproj_2090',['vector_proj',['../d2/d3b/namespaceqr__algorithm.html#a5422c76bfa322620de611083bd518d71',1,'qr_algorithm']]],
  ['vfprintf_2091',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vfscanf_2092',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vfwprintf_2093',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vfwscanf_2094',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vigenere_2095',['vigenere',['../d6/da2/namespacevigenere.html',1,'']]],
  ['vigenere_5fcipher_2ecpp_2096',['vigenere_cipher.cpp',['../dd/d12/vigenere__cipher_8cpp.html',1,'']]],
  ['vprintf_2097',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vscanf_2098',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vsnprintf_2099',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsprintf_2100',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsscanf_2101',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vswprintf_2102',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vswscanf_2103',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vwprintf_2104',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vwscanf_2105',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]]
];
