var searchData=
[
  ['va_5flist_1668',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['valarray_1669',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valid_1670',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()']]],
  ['value_1671',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()']]],
  ['value_5fcomp_1672',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()']]],
  ['value_5fcompare_1673',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map&lt; K, T &gt;::value_compare']]],
  ['value_5for_1674',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional']]],
  ['values_1675',['values',['../d2/d2c/structtower.html#a3ebb75c13c57d51a8a1ba1ea54a515e9',1,'tower']]],
  ['variance_1676',['variance',['../d7/d7c/classstatistics_1_1stats__computer1.html#a27f0a03e2fd2254f1c81fe668226bd92',1,'statistics::stats_computer1::variance()'],['../d8/dab/classstatistics_1_1stats__computer2.html#af6198817084276113b3c064e87ce0555',1,'statistics::stats_computer2::variance()']]],
  ['vector_1677',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std::vector&lt; T &gt;'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_3c_20bool_20_3e_1678',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20double_20_3e_1679',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int_20_3e_1680',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20int_2c_20int_2c_20int_20_3e_20_3e_1681',['vector&lt; std::tuple&lt; int, int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20char_20_3e_1682',['vector&lt; unsigned char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20int_20_3e_1683',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20vector_3c_20int_20_3e_20_3e_1684',['vector&lt; vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_5fdot_1685',['vector_dot',['../d2/d3b/namespaceqr__algorithm.html#a8ea313a1a1b5f9d0e3e332c29c6446ec',1,'qr_algorithm']]],
  ['vector_5fimportant_5ffunctions_2ecpp_1686',['vector_important_functions.cpp',['../d3/d61/vector__important__functions_8cpp.html',1,'']]],
  ['vector_5fmag_1687',['vector_mag',['../d2/d3b/namespaceqr__algorithm.html#ad16da2183db22378435042f26af43d5f',1,'qr_algorithm']]],
  ['vector_5fproj_1688',['vector_proj',['../d2/d3b/namespaceqr__algorithm.html#a5422c76bfa322620de611083bd518d71',1,'qr_algorithm']]],
  ['vfprintf_1689',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vfscanf_1690',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vfwprintf_1691',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vfwscanf_1692',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vprintf_1693',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vscanf_1694',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vsnprintf_1695',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsprintf_1696',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsscanf_1697',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vswprintf_1698',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vswscanf_1699',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vwprintf_1700',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vwscanf_1701',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]]
];
