var searchData=
[
  ['va_5flist_1583',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',0,'']]],
  ['valarray_1584',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',0,'std']]],
  ['valid_1585',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',0,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',0,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',0,'std::packaged_task::valid()']]],
  ['value_1586',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',0,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',0,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',0,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',0,'std::experimental::optional::value()']]],
  ['value_5fcomp_1587',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',0,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',0,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',0,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',0,'std::multimap::value_comp()']]],
  ['value_5fcompare_1588',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',0,'std::multimap&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',0,'std::map&lt; K, T &gt;::value_compare']]],
  ['value_5for_1589',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',0,'std::experimental::optional']]],
  ['values_1590',['values',['../d2/d2c/structtower.html#a3ebb75c13c57d51a8a1ba1ea54a515e9',1,'tower']]],
  ['variance_1591',['variance',['../d7/d7c/classstatistics_1_1stats__computer1.html#a27f0a03e2fd2254f1c81fe668226bd92',1,'statistics::stats_computer1::variance()'],['../d8/dab/classstatistics_1_1stats__computer2.html#af6198817084276113b3c064e87ce0555',1,'statistics::stats_computer2::variance()']]],
  ['vector_1592',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std::vector&lt; T &gt;'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',0,'std::vector::vector()']]],
  ['vector_3c_20bool_20_3e_1593',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20double_20_3e_1594',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20int_20_3e_1595',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20std_3a_3atuple_3c_20int_2c_20int_2c_20int_20_3e_20_3e_1596',['vector&lt; std::tuple&lt; int, int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20char_20_3e_1597',['vector&lt; unsigned char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20unsigned_20int_20_3e_1598',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_3c_20vector_3c_20int_20_3e_20_3e_1599',['vector&lt; vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',0,'std']]],
  ['vector_5fimportant_5ffunctions_2ecpp_1600',['vector_important_functions.cpp',['../d3/d61/vector__important__functions_8cpp.html',1,'']]],
  ['vfprintf_1601',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vfscanf_1602',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vfwprintf_1603',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vfwscanf_1604',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vprintf_1605',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vscanf_1606',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vsnprintf_1607',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsprintf_1608',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',0,'std']]],
  ['vsscanf_1609',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',0,'std']]],
  ['vswprintf_1610',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vswscanf_1611',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]],
  ['vwprintf_1612',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',0,'std']]],
  ['vwscanf_1613',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',0,'std']]]
];
